### ISSUE TITLE
List of pinned requirements / Dockerfile?

### ISSUE THREAD

**Issue by filipg7777** [sangmichaelxie/doremi#19]
I'm struggling to replicate DoReMi traning (weird errors, probably due to some incompatibility between dependencies).
Is there a list of pinned requirements (in particular what should be the version of flash_attn?). or, preferably, a Dockerfile for easy reproduction.

**Comment by sfc-gh-fgralinski** [comment]
Sorry, didn't notice that flash_attn should be v2.0.0. Anyway, the main question remains.

**Comment by filipg7777** [comment]
Sorry, didn't notice that flash_attn should be v2.0.0. Anyway, the main question remains.

**Comment by sangmichaelxie** [comment]
The requirements should be here: https://raw.githubusercontent.com/sangmichaelxie/doremi/main/setup.py
