### ISSUE TITLE
Question about the initialization of the perdomain_scores

### ISSUE THREAD

**Issue by yuzc19** [sangmichaelxie/doremi#26]
Hi, I noticed that the perdomain_scores are initialized with np.log(len(tokenizer)). Is it because you assume that the random model will generate a uniform distribution over the vocabulary? Thank you!

https://github.com/sangmichaelxie/doremi/blob/7cde52d1848737aa967ecbdb9e643cf334de160d/doremi/train.py#L273

**Comment by sangmichaelxie** [comment]
Yes, although in the first iteration usually there is an example from each domain so this initial value usually doesn't get included in the moving average.
