### ISSUE TITLE
Question about 8B model architecture

### ISSUE THREAD

**Issue by Qinghao-Hu** [sangmichaelxie/doremi#28]
Thanks for your interesting work!

Could you please provide the configuration of the 8B model?

How do you generate the proxy model? Is it generated based on 8B? Or just a smaller model with arbitrary configuration (e.g., layer num)?

**Comment by sangmichaelxie** [comment]
Please see Table 9 here: https://arxiv.org/pdf/2305.10429

The proxy model is just a smaller model (less layers, heads, hidden dims)
