### ISSUE TITLE
question about domain weights initialization value in paper fingure 8

### ISSUE THREAD

**Issue by Haijunlv** [sangmichaelxie/doremi#7]
Thx for the amazing paper and open codebase!  I have one question about paper fingure 8.
The domain weights initialization value  in figure 8 (step 0)  seems not equal as the Algorithm 1 Initialize domain weights α0 = 1/k.
And  domain weights initialization in figure 8a is also not equal with  figure 8b.
So what is the domain weights initialization strategy in figure 8?

![image](https://github.com/sangmichaelxie/doremi/assets/28926237/b2350f89-8b57-45b0-b2aa-3483a0f32307)
![image](https://github.com/sangmichaelxie/doremi/assets/28926237/5504bb20-1f11-4c4b-a1bb-8c1b77493f1b)

**Comment by sangmichaelxie** [comment]
The initialization is uniform, it's just that the plot doesn't start at step 0, and the plot is an exponential moving average over time steps.
